In [7]:
import kagglehub
import pandas as pd
import os

# Modul 1

In [2]:
path  = kagglehub.dataset_download('wowevan/dataset-kesejahteraan-pekerja-indonesia')


print(path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/wowevan/dataset-kesejahteraan-pekerja-indonesia?dataset_version_number=1...

100%|██████████| 76.4k/76.4k [00:00<00:00, 525kB/s]

Extracting files...
/root/.cache/kagglehub/datasets/wowevan/dataset-kesejahteraan-pekerja-indonesia/versions/1

In [12]:
os.listdir(path)

['rataRataUpah.csv', 'pengeluaran.csv', 'minUpah.csv', 'garisKemiskinan.csv']

In [9]:
data = pd.read_csv(f'{path}/rataRataUpah.csv')

### Jenis data

Terdapat 1 data nominal dan 2 data kuantitatif, yaitu data pada kolom provinsi sebagai data nominal serta kolom tahun dan upah sebagai data kuantitaf.

In [10]:
data.head(10)

         provinsi  tahun   upah
0            ACEH   2015  11226
1            ACEH   2016  13627
2            ACEH   2017  14809
3            ACEH   2018  13814
4            ACEH   2019  15065
5            ACEH   2020  18099
6            ACEH   2021  17037
7            ACEH   2022  16772
8  SUMATERA UTARA   2015  10618
9  SUMATERA UTARA   2016  11646

# Modul 2

In [11]:
dataset_path = kagglehub.dataset_download('halaturkialotaibi/coffee-bean-sales-dataset')

print(dataset_path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/halaturkialotaibi/coffee-bean-sales-dataset?dataset_version_number=2...

100%|██████████| 8.91k/8.91k [00:00<00:00, 10.9MB/s]

Extracting files...
/root/.cache/kagglehub/datasets/halaturkialotaibi/coffee-bean-sales-dataset/versions/2

In [13]:
os.listdir(dataset_path)

['DatasetForCoffeeSales2.csv', 'saudi_cities_geocoding.csv']

In [24]:
sales_data = pd.read_csv(f'{dataset_path}/DatasetForCoffeeSales2.csv')

In [25]:
len(sales_data)

730

In [26]:
sales_data.head(20)

,Date,Customer_ID,City,Category,Product,Unit Price,Quantity,Sales Amount,Used_Discount,Discount_Amount,Final Sales
0,1/1/2023,32,Riyadh,coffee beans,Colombian,40,14,560,False,0,560
1,1/2/2023,49,Abha,coffee beans,Costa Rica,35,17,595,False,0,595
2,1/3/2023,75,Tabuk,coffee beans,Costa Rica,35,19,665,False,0,665
3,1/4/2023,80,Abha,coffee beans,Ethiopian,45,1,45,False,0,45
4,1/5/2023,78,Hail,coffee beans,Colombian,40,46,1840,True,368,1472
5,1/6/2023,1,Khobar,coffee beans,Colombian,40,32,1280,True,256,1024
6,1/7/2023,95,Buraidah,coffee beans,Brazilian,30,1,30,True,6,24
7,1/8/2023,27,Medina,coffee beans,Colombian,40,33,1320,False,0,1320
8,1/9/2023,73,Hail,coffee beans,Guatemala,35,47,1645,False,0,1645
9,1/10/2023,82,Dammam,coffee beans,Costa Rica,35,4,140,False,0,140
10,1/11/2023,63,Tabuk,coffee beans,Guatemala,35,6,210,False,0,210
11,1/12/2023,3,Medina,coffee beans,Brazilian,30,14,420,False,0,420
12,1/13/2023,71,Dammam,coffee beans,Costa Rica,35,47,1645,False,0,1645
13,1/14/2023,50,Jeddah,coffee beans,Costa Rica,35,47,1645,False,0,1645
14,1/15/2023,62,Mecca,coffee beans,Brazilian,30,2,60,False,0,60
15,1/16/2023,36,Jeddah,coffee beans,Ethiopian,45,49,2205,True,441,1764
16,1/17/2023,61,Khobar,coffee beans,Colombian,40,4,160,True,32,128
17,1/18/2023,58,Dammam,coffee beans,Colombian,40,45,1800,False,0,1800
18,1/19/2023,3,Jeddah,coffee beans,Ethiopian,45,48,2160,False,0,2160
19,1/20/2023,2,Riyadh,coffee beans,Ethiopian,45,18,810,True,162,648

In [28]:
sales_data.filter(['City' , 'Category' , 'Product' , 'Quantity']).head()

     City      Category     Product  Quantity
0  Riyadh  coffee beans   Colombian        14
1    Abha  coffee beans  Costa Rica        17
2   Tabuk  coffee beans  Costa Rica        19
3    Abha  coffee beans   Ethiopian         1
4    Hail  coffee beans   Colombian        46

In [31]:
sales_data.sort_values("Quantity" , axis=0, ascending=False , inplace = True ,  na_position = 'last')
display(sales_data.head())

,Date,Customer_ID,City,Category,Product,Unit Price,Quantity,Sales Amount,Used_Discount,Discount_Amount,Final Sales
696,11/27/2024,80,Buraidah,coffee beans,Colombian,40,49,1960,True,392,1568
355,12/22/2023,31,Buraidah,coffee beans,Brazilian,30,49,1470,False,0,1470
577,7/31/2024,65,Dammam,coffee beans,Colombian,40,49,1960,True,392,1568
149,5/30/2023,4,Abha,coffee beans,Costa Rica,35,49,1715,False,0,1715
542,6/26/2024,89,Khobar,coffee beans,Brazilian,30,49,1470,True,294,1176

In [32]:
sales_data_groupby_city = sales_data.groupby('City')

result = sales_data_groupby_city['Final Sales'].agg('sum')

In [33]:
result

City
Abha        52831
Buraidah    56875
Dammam      59975
Hail        77257
Jeddah      72048
Khobar      59989
Mecca       66420
Medina      64813
Riyadh      68421
Tabuk       51019
Name: Final Sales, dtype: int64

# Modul 3

In [34]:
!gdown 1ZWpS_EKAvbsvuigBXDaH0p01FahpHeh8

Downloading...
From: https://drive.google.com/uc?id=1ZWpS_EKAvbsvuigBXDaH0p01FahpHeh8
To: /content/students.csv
100% 61.6k/61.6k [00:00<00:00, 64.4MB/s]

In [58]:
student_data = pd.read_csv('students.csv')

In [50]:
student_data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,grade
0,female,group B,bachelor's degree,standard,none,72,72.0,74,8.0
1,female,group C,some college,standard,completed,69,90.0,88,7.0
2,female,group B,master's degree,standard,none,90,95.0,93,7.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44,8.0
4,male,group C,some college,standard,none,76,78.0,75,8.0

In [51]:
student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        975 non-null    object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                976 non-null    float64
 7   writing score                1000 non-null   int64
 8   grade                        985 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 70.4+ KB

In [64]:
student_data.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
grade                          0
dtype: int64

In [66]:
student_data['lunch'].interpolate(methode='linear', inplace=True)

<ipython-input-66-1700bb6163e1>:1: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  student_data['lunch'].interpolate(methode='linear', inplace=True)

In [47]:
student_data.groupby('lunch').agg({'lunch' : 'count'})

              lunch
lunch
free/reduced    344
standard        656

In [59]:
student_data['lunch'].fillna(student_data['lunch'].mode()[0] , inplace=True)

<ipython-input-59-388ba16654ba>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_data['lunch'].fillna(student_data['lunch'].mode()[0] , inplace=True)

In [60]:
student_data['reading score'].fillna(student_data['reading score'].mean() , inplace=True)

<ipython-input-60-7df032eca5e6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_data['reading score'].fillna(student_data['reading score'].mean() , inplace=True)

In [63]:
student_data['grade'].fillna(student_data['grade'].median() , inplace=True)

<ipython-input-63-61e836c49db1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_data['grade'].fillna(student_data['grade'].median() , inplace=True)